modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/pandoras-creatures/issues"
logoFile="logo.png"
license="MIT"

[[mods]]
    modId="pandoras_creatures"
	version="1.16.3-2.0.1"
	displayName="Pandoras Creatures"
	updateJSONURL="https://raw.githubusercontent.com/andrew0030/Pandoras-Creatures/master/src/main/resources/assets/pandoras_creatures/update.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/pandoras-creatures"
	credits="\nIgrek, for his amazing textures.\nFlummie2000 for translating and textures.\nGdG_Metiu19 for translating.\nqsefthuopq for translating.\nGhanou Craft for translating.\nEl Limbo for translating.\nGun_Man1 for translating.\nWanadi for translating.\nMinzhire for translating.\n"
	authors="andrew0030\n"
	description='''
Pandoras Creatures is a Mod that aims to make your game experience harder. If you got bored of the normal mobs or just want to walk around and enjoy exploring the new creatures and how they affect the world, then this Mod is exactly what you need.
	'''

[[dependencies.pandoras_creatures]] #optional
    modId="forge"
    mandatory=true
    versionRange="[34.1.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pandoras_creatures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
